on:
  pull_request:
  push:
    branches: main
name: Linkinator
jobs:
  linkinator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JustinBeckwith/linkinator-action@v1
        with:
          paths: "**/*.md*"
          markdown: true
          recurse: true
          # Temp added broken link below : https://github.com/ethereum/solidity/pull/11843%5Bethereum/solidity
          linksToSkip: "https://opensea.io, http://localhost:3000, assets/, /assets, https://support.discord.com, https://www.pokemoncenter.com, https://collab.land/, https://polygonscan.com/, https://etherscan.io/, https://rinkeby.etherscan.io/, https://goerli.etherscan.io/, https://github.com/ethereum/solidity/pull/11843%5Bethereum/solidity"
